/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as NeedsRouteImport } from './routes/needs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as HelpRouteImport } from './routes/help'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DiagRouteImport } from './routes/diag'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as NeedsIndexRouteImport } from './routes/needs.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as HelpIndexRouteImport } from './routes/help.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ReviewsVerifiedHireIdRouteImport } from './routes/reviews.$verifiedHireId'
import { Route as ReviewEmployerTokenRouteImport } from './routes/review-employer.$token'
import { Route as PostsIdRouteImport } from './routes/posts.$id'
import { Route as PUsernameRouteImport } from './routes/p.$username'
import { Route as OpportunitiesNewRouteImport } from './routes/opportunities.new'
import { Route as NeedsNewRouteImport } from './routes/needs.new'
import { Route as JobsHireRequestRouteImport } from './routes/jobs.hire-request'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as HelpSlugRouteImport } from './routes/help.$slug'
import { Route as EmployerTokenRouteImport } from './routes/employer.$token'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardServicesRouteImport } from './routes/dashboard.services'
import { Route as DashboardSavesRouteImport } from './routes/dashboard.saves'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard.reviews'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard.referrals'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardOpportunitiesRouteImport } from './routes/dashboard.opportunities'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardNeedsRouteImport } from './routes/dashboard.needs'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardJobsRouteImport } from './routes/dashboard.jobs'
import { Route as DashboardHelpRouteImport } from './routes/dashboard.help'
import { Route as DashboardEventsRouteImport } from './routes/dashboard.events'
import { Route as DashboardBusinessProfileRouteImport } from './routes/dashboard.business-profile'
import { Route as DashboardApplicationsRouteImport } from './routes/dashboard.applications'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as BillingSuccessRouteImport } from './routes/billing.success'
import { Route as BillingStartRouteImport } from './routes/billing.start'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedsRoute = NeedsRouteImport.update({
  id: '/needs',
  path: '/needs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagRoute = DiagRouteImport.update({
  id: '/diag',
  path: '/diag',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const NeedsIndexRoute = NeedsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NeedsRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HelpRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ReviewsVerifiedHireIdRoute = ReviewsVerifiedHireIdRouteImport.update({
  id: '/reviews/$verifiedHireId',
  path: '/reviews/$verifiedHireId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewEmployerTokenRoute = ReviewEmployerTokenRouteImport.update({
  id: '/review-employer/$token',
  path: '/review-employer/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PUsernameRoute = PUsernameRouteImport.update({
  id: '/p/$username',
  path: '/p/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesNewRoute = OpportunitiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const NeedsNewRoute = NeedsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => NeedsRoute,
} as any)
const JobsHireRequestRoute = JobsHireRequestRouteImport.update({
  id: '/hire-request',
  path: '/hire-request',
  getParentRoute: () => JobsRoute,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JobsRoute,
} as any)
const HelpSlugRoute = HelpSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HelpRoute,
} as any)
const EmployerTokenRoute = EmployerTokenRouteImport.update({
  id: '/employer/$token',
  path: '/employer/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSavesRoute = DashboardSavesRouteImport.update({
  id: '/saves',
  path: '/saves',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOpportunitiesRoute = DashboardOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNeedsRoute = DashboardNeedsRouteImport.update({
  id: '/needs',
  path: '/needs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusinessProfileRoute =
  DashboardBusinessProfileRouteImport.update({
    id: '/business-profile',
    path: '/business-profile',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardApplicationsRoute = DashboardApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingStartRoute = BillingStartRouteImport.update({
  id: '/billing/start',
  path: '/billing/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/diag': typeof DiagRoute
  '/events': typeof EventsRoute
  '/help': typeof HelpRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/needs': typeof NeedsRouteWithChildren
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/referrals': typeof ReferralsRoute
  '/safety': typeof SafetyRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/billing/start': typeof BillingStartRoute
  '/billing/success': typeof BillingSuccessRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/business-profile': typeof DashboardBusinessProfileRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/needs': typeof DashboardNeedsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/opportunities': typeof DashboardOpportunitiesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/saves': typeof DashboardSavesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/employer/$token': typeof EmployerTokenRoute
  '/help/$slug': typeof HelpSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/hire-request': typeof JobsHireRequestRoute
  '/needs/new': typeof NeedsNewRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/p/$username': typeof PUsernameRoute
  '/posts/$id': typeof PostsIdRoute
  '/review-employer/$token': typeof ReviewEmployerTokenRoute
  '/reviews/$verifiedHireId': typeof ReviewsVerifiedHireIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/help/': typeof HelpIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/needs/': typeof NeedsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/diag': typeof DiagRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/referrals': typeof ReferralsRoute
  '/safety': typeof SafetyRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/billing/start': typeof BillingStartRoute
  '/billing/success': typeof BillingSuccessRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/business-profile': typeof DashboardBusinessProfileRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/needs': typeof DashboardNeedsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/opportunities': typeof DashboardOpportunitiesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/saves': typeof DashboardSavesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/employer/$token': typeof EmployerTokenRoute
  '/help/$slug': typeof HelpSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/hire-request': typeof JobsHireRequestRoute
  '/needs/new': typeof NeedsNewRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/p/$username': typeof PUsernameRoute
  '/posts/$id': typeof PostsIdRoute
  '/review-employer/$token': typeof ReviewEmployerTokenRoute
  '/reviews/$verifiedHireId': typeof ReviewsVerifiedHireIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/help': typeof HelpIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/needs': typeof NeedsIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/diag': typeof DiagRoute
  '/events': typeof EventsRoute
  '/help': typeof HelpRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/needs': typeof NeedsRouteWithChildren
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/referrals': typeof ReferralsRoute
  '/safety': typeof SafetyRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/billing/start': typeof BillingStartRoute
  '/billing/success': typeof BillingSuccessRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/business-profile': typeof DashboardBusinessProfileRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/needs': typeof DashboardNeedsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/opportunities': typeof DashboardOpportunitiesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/saves': typeof DashboardSavesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/employer/$token': typeof EmployerTokenRoute
  '/help/$slug': typeof HelpSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/hire-request': typeof JobsHireRequestRoute
  '/needs/new': typeof NeedsNewRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/p/$username': typeof PUsernameRoute
  '/posts/$id': typeof PostsIdRoute
  '/review-employer/$token': typeof ReviewEmployerTokenRoute
  '/reviews/$verifiedHireId': typeof ReviewsVerifiedHireIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/help/': typeof HelpIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/needs/': typeof NeedsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/diag'
    | '/events'
    | '/help'
    | '/jobs'
    | '/login'
    | '/needs'
    | '/opportunities'
    | '/pricing'
    | '/privacy'
    | '/referrals'
    | '/safety'
    | '/search'
    | '/signup'
    | '/terms'
    | '/billing/start'
    | '/billing/success'
    | '/dashboard/analytics'
    | '/dashboard/applications'
    | '/dashboard/business-profile'
    | '/dashboard/events'
    | '/dashboard/help'
    | '/dashboard/jobs'
    | '/dashboard/leads'
    | '/dashboard/needs'
    | '/dashboard/notifications'
    | '/dashboard/opportunities'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/reviews'
    | '/dashboard/saves'
    | '/dashboard/services'
    | '/dashboard/team'
    | '/employer/$token'
    | '/help/$slug'
    | '/jobs/$id'
    | '/jobs/hire-request'
    | '/needs/new'
    | '/opportunities/new'
    | '/p/$username'
    | '/posts/$id'
    | '/review-employer/$token'
    | '/reviews/$verifiedHireId'
    | '/dashboard/'
    | '/help/'
    | '/jobs/'
    | '/needs/'
    | '/opportunities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/diag'
    | '/events'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/referrals'
    | '/safety'
    | '/search'
    | '/signup'
    | '/terms'
    | '/billing/start'
    | '/billing/success'
    | '/dashboard/analytics'
    | '/dashboard/applications'
    | '/dashboard/business-profile'
    | '/dashboard/events'
    | '/dashboard/help'
    | '/dashboard/jobs'
    | '/dashboard/leads'
    | '/dashboard/needs'
    | '/dashboard/notifications'
    | '/dashboard/opportunities'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/reviews'
    | '/dashboard/saves'
    | '/dashboard/services'
    | '/dashboard/team'
    | '/employer/$token'
    | '/help/$slug'
    | '/jobs/$id'
    | '/jobs/hire-request'
    | '/needs/new'
    | '/opportunities/new'
    | '/p/$username'
    | '/posts/$id'
    | '/review-employer/$token'
    | '/reviews/$verifiedHireId'
    | '/dashboard'
    | '/help'
    | '/jobs'
    | '/needs'
    | '/opportunities'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/diag'
    | '/events'
    | '/help'
    | '/jobs'
    | '/login'
    | '/needs'
    | '/opportunities'
    | '/pricing'
    | '/privacy'
    | '/referrals'
    | '/safety'
    | '/search'
    | '/signup'
    | '/terms'
    | '/billing/start'
    | '/billing/success'
    | '/dashboard/analytics'
    | '/dashboard/applications'
    | '/dashboard/business-profile'
    | '/dashboard/events'
    | '/dashboard/help'
    | '/dashboard/jobs'
    | '/dashboard/leads'
    | '/dashboard/needs'
    | '/dashboard/notifications'
    | '/dashboard/opportunities'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/reviews'
    | '/dashboard/saves'
    | '/dashboard/services'
    | '/dashboard/team'
    | '/employer/$token'
    | '/help/$slug'
    | '/jobs/$id'
    | '/jobs/hire-request'
    | '/needs/new'
    | '/opportunities/new'
    | '/p/$username'
    | '/posts/$id'
    | '/review-employer/$token'
    | '/reviews/$verifiedHireId'
    | '/dashboard/'
    | '/help/'
    | '/jobs/'
    | '/needs/'
    | '/opportunities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DiagRoute: typeof DiagRoute
  EventsRoute: typeof EventsRoute
  HelpRoute: typeof HelpRouteWithChildren
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  NeedsRoute: typeof NeedsRouteWithChildren
  OpportunitiesRoute: typeof OpportunitiesRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReferralsRoute: typeof ReferralsRoute
  SafetyRoute: typeof SafetyRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  BillingStartRoute: typeof BillingStartRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
  EmployerTokenRoute: typeof EmployerTokenRoute
  PUsernameRoute: typeof PUsernameRoute
  PostsIdRoute: typeof PostsIdRoute
  ReviewEmployerTokenRoute: typeof ReviewEmployerTokenRoute
  ReviewsVerifiedHireIdRoute: typeof ReviewsVerifiedHireIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needs': {
      id: '/needs'
      path: '/needs'
      fullPath: '/needs'
      preLoaderRoute: typeof NeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diag': {
      id: '/diag'
      path: '/diag'
      fullPath: '/diag'
      preLoaderRoute: typeof DiagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/needs/': {
      id: '/needs/'
      path: '/'
      fullPath: '/needs/'
      preLoaderRoute: typeof NeedsIndexRouteImport
      parentRoute: typeof NeedsRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/help/': {
      id: '/help/'
      path: '/'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof HelpRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/reviews/$verifiedHireId': {
      id: '/reviews/$verifiedHireId'
      path: '/reviews/$verifiedHireId'
      fullPath: '/reviews/$verifiedHireId'
      preLoaderRoute: typeof ReviewsVerifiedHireIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-employer/$token': {
      id: '/review-employer/$token'
      path: '/review-employer/$token'
      fullPath: '/review-employer/$token'
      preLoaderRoute: typeof ReviewEmployerTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$username': {
      id: '/p/$username'
      path: '/p/$username'
      fullPath: '/p/$username'
      preLoaderRoute: typeof PUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/new': {
      id: '/opportunities/new'
      path: '/new'
      fullPath: '/opportunities/new'
      preLoaderRoute: typeof OpportunitiesNewRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/needs/new': {
      id: '/needs/new'
      path: '/new'
      fullPath: '/needs/new'
      preLoaderRoute: typeof NeedsNewRouteImport
      parentRoute: typeof NeedsRoute
    }
    '/jobs/hire-request': {
      id: '/jobs/hire-request'
      path: '/hire-request'
      fullPath: '/jobs/hire-request'
      preLoaderRoute: typeof JobsHireRequestRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/help/$slug': {
      id: '/help/$slug'
      path: '/$slug'
      fullPath: '/help/$slug'
      preLoaderRoute: typeof HelpSlugRouteImport
      parentRoute: typeof HelpRoute
    }
    '/employer/$token': {
      id: '/employer/$token'
      path: '/employer/$token'
      fullPath: '/employer/$token'
      preLoaderRoute: typeof EmployerTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/saves': {
      id: '/dashboard/saves'
      path: '/saves'
      fullPath: '/dashboard/saves'
      preLoaderRoute: typeof DashboardSavesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/opportunities': {
      id: '/dashboard/opportunities'
      path: '/opportunities'
      fullPath: '/dashboard/opportunities'
      preLoaderRoute: typeof DashboardOpportunitiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/needs': {
      id: '/dashboard/needs'
      path: '/needs'
      fullPath: '/dashboard/needs'
      preLoaderRoute: typeof DashboardNeedsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/help': {
      id: '/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-profile': {
      id: '/dashboard/business-profile'
      path: '/business-profile'
      fullPath: '/dashboard/business-profile'
      preLoaderRoute: typeof DashboardBusinessProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/applications': {
      id: '/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof DashboardApplicationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/start': {
      id: '/billing/start'
      path: '/billing/start'
      fullPath: '/billing/start'
      preLoaderRoute: typeof BillingStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardApplicationsRoute: typeof DashboardApplicationsRoute
  DashboardBusinessProfileRoute: typeof DashboardBusinessProfileRoute
  DashboardEventsRoute: typeof DashboardEventsRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardNeedsRoute: typeof DashboardNeedsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOpportunitiesRoute: typeof DashboardOpportunitiesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardSavesRoute: typeof DashboardSavesRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardApplicationsRoute: DashboardApplicationsRoute,
  DashboardBusinessProfileRoute: DashboardBusinessProfileRoute,
  DashboardEventsRoute: DashboardEventsRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardNeedsRoute: DashboardNeedsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOpportunitiesRoute: DashboardOpportunitiesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSavesRoute: DashboardSavesRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface HelpRouteChildren {
  HelpSlugRoute: typeof HelpSlugRoute
  HelpIndexRoute: typeof HelpIndexRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpSlugRoute: HelpSlugRoute,
  HelpIndexRoute: HelpIndexRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

interface JobsRouteChildren {
  JobsIdRoute: typeof JobsIdRoute
  JobsHireRequestRoute: typeof JobsHireRequestRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsIdRoute: JobsIdRoute,
  JobsHireRequestRoute: JobsHireRequestRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface NeedsRouteChildren {
  NeedsNewRoute: typeof NeedsNewRoute
  NeedsIndexRoute: typeof NeedsIndexRoute
}

const NeedsRouteChildren: NeedsRouteChildren = {
  NeedsNewRoute: NeedsNewRoute,
  NeedsIndexRoute: NeedsIndexRoute,
}

const NeedsRouteWithChildren = NeedsRoute._addFileChildren(NeedsRouteChildren)

interface OpportunitiesRouteChildren {
  OpportunitiesNewRoute: typeof OpportunitiesNewRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
}

const OpportunitiesRouteChildren: OpportunitiesRouteChildren = {
  OpportunitiesNewRoute: OpportunitiesNewRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
}

const OpportunitiesRouteWithChildren = OpportunitiesRoute._addFileChildren(
  OpportunitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DiagRoute: DiagRoute,
  EventsRoute: EventsRoute,
  HelpRoute: HelpRouteWithChildren,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  NeedsRoute: NeedsRouteWithChildren,
  OpportunitiesRoute: OpportunitiesRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReferralsRoute: ReferralsRoute,
  SafetyRoute: SafetyRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  BillingStartRoute: BillingStartRoute,
  BillingSuccessRoute: BillingSuccessRoute,
  EmployerTokenRoute: EmployerTokenRoute,
  PUsernameRoute: PUsernameRoute,
  PostsIdRoute: PostsIdRoute,
  ReviewEmployerTokenRoute: ReviewEmployerTokenRoute,
  ReviewsVerifiedHireIdRoute: ReviewsVerifiedHireIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'

import type { startInstance } from './start.ts'

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true

    router: Awaited<ReturnType<typeof getRouter>>

    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
